import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { initializeFirestore, memoryLocalCache } from 'firebase/firestore';

// In AI Studio, this file is automatically generated by the set_up_firebase tool.
// If it's missing, we'll use placeholders that will be replaced during the build.
import { firebaseConfig } from './firebase-config';

const app = initializeApp(firebaseConfig);
export const db = initializeFirestore(app, {
  localCache: memoryLocalCache()
}, firebaseConfig.firestoreDatabaseId || '(default)');
export const auth = getAuth(app);

export default app;
